config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "pages#home"
    # root to: "tasks#index"

  get "score", to: "tasks#score", as: :score
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks do
    get :duplicate, on: :member
    resources :templates, only: [:new, :create]
  end
  # Defines the root path route ("/")
  post "tasks/:id/mark_as_done", to: "tasks#mark_as_done", as: :mark_as_done

  resources :templates do
    resources :tasks, only: [:new, :create]
  end
  # root "articles#index"
  resources :contacts
end

# resources :categories, only: [:index, :show] ??
# resources :templates, only: [:index, :show]
# resources :kids, only [:show, :create]
# resources :housholds, only [:index]

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user
  belongs_to :household
  belongs_to :kid, optional: true
  belongs_to :contact, optional: true
  belongs_to :assigned_to, class_name: "User", optional: true
  validates :name, presence: true
  validates :category, presence: true
  validates :points, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = policy_scope(Task)
    if params[:query].present?
      sql_query = "tasks.name ILIKE :query OR categories.name ILIKE :query"
      @tasks = policy_scope(Task.joins(:category).where(sql_query, query: "%#{params[:query]}%"))
    else
      @tasks = policy_scope(Task)
    end
    #for bar chart:
    user_ids = current_user.household.users.pluck(:id)
    user_ids.delete(current_user.id)
    partner_id = user_ids.first
    all_tasks = Task.all
    # @user_tasks = current_user.tasks.where(done: true)
    @user_tasks = all_tasks.where(assigned_to: current_user.household.users.reject { |user| user.id == partner_id }[0]).and(all_tasks.where(done: true))
    @partner_tasks = all_tasks.where(assigned_to: current_user.household.users.reject { |user| user.id == current_user.id }[0]).and(all_tasks.where(done: true))
  end

  def show
    @task = Task.find(params[:id])
    authorize @task
  end

  def mark_as_done
    @task = Task.find(params[:id])
    authorize @task
    if @task.done = true
      @task.done = false
    else
      @task.done = true
    end
    @task.save!
    redirect_to tasks_path
  end

  def score
    user_ids = current_user.household.users.pluck(:id)
    user_ids.delete(current_user.id)
    partner_id = user_ids.first
    @tasks = Task.all
    # @user_tasks = current_user.tasks.where(done: true)
    @user_tasks = @tasks.where(assigned_to: current_user.household.users.reject { |user| user.id == partner_id }[0]).and(@tasks.where(done: true))
    @partner_tasks = @tasks.where(assigned_to: current_user.household.users.reject { |user| user.id == current_user.id }[0]).and(@tasks.where(done: true))
    @unassigned_tasks = Task.where(household_id: current_user.household_id).and(Task.where(assigned_to_id: nil))

    authorize @user_tasks
    authorize @partner_tasks
    authorize @unassigned_tasks
  end

  def new
    if params[:template_id]
      @template = Template.find(params[:template_id])
      @task = Task.new(name: @template.name, points: @template.points, duration: @template.duration, comments: @template.comments, type: @template.type, category: @template.category)
    else
      @task = Task.new
    end
    authorize @task
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    @task.household = current_user.household
    authorize @task
    if @task.save
      redirect_to tasks_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
    authorize @task
  end

  def update
    @task = Task.find(params[:id])
    authorize @task
    @task.update(task_params)
      respond_to do |format|
        format.html { redirect_to tasks_path }
        format.text { render partial: "tasks/task", locals: {task: @task}, formats: [:html] }
      end
  end

  def duplicate
    @task = Task.find(params[:id]).dup
    authorize @task
  end

  def destroy
    @task = Task.find(params[:id])
    authorize @task
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :points, :duration, :type, :comments, :contact_id, :due_date, :status, :done, :assigned_to_id, :category_id)
  end
end

app/views/tasks/_form.html.erb
<div class="row">
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :name, input_wrapper_html: { class: 'col-sm-4 text-left' }, error: 'You must add a name to the task', placeholder: "add task name" %>
    <%= f.input :points %>
      <div class="col">
        <%= f.input :due_date, as: :string,
                    wrapper_html: { class: "mb-4" },
                    label_html: { class: "w-100 text-left" },
                    input_html: { data: { controller: "flatpickr" } } %>
      </div>
    <%= f.association :contact, collection: Contact.where(household: current_user.household).map {|contact|[contact.title, contact.id]} %>
    <%= f.association :category, collection: Category.all, error: 'You must choose one category', prompt: "Select a category"%>
    <%= f.association :assigned_to, collection: User.where(household: current_user.household).map{ |user| [user.username, user.id]}, prompt: "unassigned"%>
    <div class="d-flex w-100 justify-content-around align-items-center">

      <%= link_to tasks_path do %><i class="form-button fa-solid fa-chevron-left fa-lg"></i>
      <% end  %>
        <%= f.submit :"Save", class: "btn btn-add mt-1" %>
      <%= link_to tasks_path do %><i class="form-button fa-solid fa-trash fa-lg"></i>
      <% end  %></div>
  <% end %>
</div>

<%#= f.input :subdomain, input_wrapper_html: { class: 'col-sm-4' } %>

app/views/tasks/_task.html.erb
<div class='<%= task.done? ? "task-card-completed" : "task-card" %>' data-controller="mark" data-mark-target="task">
  <div class="task-infos">
    <% category_hash = {
      "Groceries" => "🥕",
      "Care" => "🐣",
      "Cleaning" => "🧽",
      "Paperwork" => "📄",
      "Planning" => "📅",
      "Maintenance" => "💡"
    } %>
    <p><span><%= category_hash[task.category.name] %>  </span> <%= task.category.name %></p>
    <div class="task-circles">
      <div class="task-points">
        <p><%= task.points %></p>
      </div>
      <div class="assigned_to" style="background-color: <%= task.assigned_to.nil? ? 'grey' : task.assigned_to.color %>">
        <p><%= task.assigned_to.nil? ? "?" : task.assigned_to.username[0] %></p>
      </div>
    </div>
  </div>
  <div class="task-name" >
    <%= simple_form_for task, html: {
      class: "",
        data: { mark_target: "form" }
      } do |f| %>
      <%= f.input :done, label: false, input_html: { data: { action: "change->mark#check" }, class: "task-checkbox" } %>
    <% end %>
    <%= link_to(task_path(task)) do %>
      <h4><%= task.name %></h4>
    <% end %>
  </div>
</div>

app/views/tasks/duplicate.html.erb
<%= render "form", task: @task %>

app/views/tasks/edit.html.erb
<div class="welcome-message">
  <h1>Edit Task</h1>
</div>
   <div class= "main-card">
    <div class="task-name-card justify-content-center">
      <h4><%= @task.name %></h4>
    </div>

<div class="container">
  <%= render "form", task: @task %>
  <div style="height: 120px"></div>
</div>

app/views/tasks/index.html.erb
<div class="main-div" data-controller="filter-tasks">
  <div class="button-container container d-flex justify-content-center flex-grow sticky-top pt-3 pb-3">
    <div class="button-box d-flex flex-grow">
      <div class="btn btn-menu btn-active" data-filter-tasks-target="navButton">
        <p data-action="click->filter-tasks#show" class="all"> All</p>
      </div>
      <div class="btn btn-menu" data-filter-tasks-target="navButton">
        <p data-action="click->filter-tasks#show" class="user"> <%= current_user.username.capitalize %></p>
      </div>
      <div class="btn btn-menu" data-filter-tasks-target="navButton">
        <p data-action="click->filter-tasks#show" class="partner"><%= current_user.household.users.reject { |user| user.id == current_user.id }[0].username.capitalize %></p>
      </div>
      <div class="btn btn-menu" data-filter-tasks-target="navButton">
        <p data-action="click->filter-tasks#show" class="open"> Open</p>
      </div>
    </div>
  </div>
<div class="hello container">
  <h1>Hello <%= current_user.username %>!</h1>
  <div class="hello-names d-none">
    <div class="hello-user">
      <p><%= current_user.username %></p>
    </div>
    <div class="hello-partner">
      <p><%= current_user.household.users.reject { |user| user.id == current_user.id }[0].username.capitalize %></p>
    </div>
  </div>
  <div class="hello-stat-names" >
    <% @user_sum = @user_tasks.pluck(:points).sum %>
    <% @partner_sum = @partner_tasks.pluck(:points).sum%>
    <% @all_sum = @user_sum + @partner_sum%>
    <% if @all_sum.zero? %>
      <% @user_per = 50 %>
      <% @partner_per = 50%>
    <% else %>
      <% @user_per = (100.0*@user_sum/@all_sum).round %>
      <% @partner_per = (100.0*@partner_sum/@all_sum).round %>
    <% end %>
    <div class="hello-stat-user" style='<%="width: #{@user_per}%"%>'>
      <p><%= "#{@user_per}%" %></p>
    </div>
    <div class="hello-stat-partner" style='<%="width: #{@partner_per}%"%>'>
      <p><%= "#{@partner_per}%" %></p>
    </div>
  </div>
</div>
  <div class="container search overflow-fix mt-3 pt-2">
    <%= form_with url: tasks_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "find task"
      %>
      <%= submit_tag "Search", class: "btn btn-flat" %>
    <% end %>
  </div>
  <div class="container d-flex" data-filter-tasks-target="allSwitch">
    <div class="form-check form-switch" >
      <input data-action="click->filter-tasks#doneAll" class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
      <label class="form-check-label" for="flexSwitchCheckDefault">undone/done</label>
    </div>
  </div>
  <div data-filter-tasks-target="allTasks" class="container pl-2 overflow-fix">
    <% @tasks.where(done: false).each do |task| %>
      <%= render "task", task: task %>
    <% end %>
  </div>
  <div data-filter-tasks-target="allTasksA" class="container pl-2 overflow-fix">
    <% @tasks.where(done: true).each do |task| %>
      <%= render "task", task: task %>
    <% end %>
  </div>

   <div class="container d-flex d-none" data-filter-tasks-target="currentUserSwitch">
    <div class="form-check form-switch">
      <input data-action="click->filter-tasks#doneCurrentUser" class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
      <label class="form-check-label" for="flexSwitchCheckDefault">undone/done</label>
    </div>
  </div>
  <div data-filter-tasks-target="currentUser" class="container pl-2 overflow-fix d-none">
    <% @tasks.where(assigned_to: current_user).and(@tasks.where(done: false)).each do |task| %>
      <%= render "task", task: task %>
    <% end %>
  </div>
  <div data-filter-tasks-target="currentUserA" class="container pl-2 overflow-fix d-none">
    <% @tasks.where(assigned_to: current_user).and(@tasks.where(done: true)).each do |task| %>
      <%= render "task", task: task %>
    <% end %>
  </div>


   <div class="container d-flex d-none" data-filter-tasks-target="userPartnerSwitch">
    <div class="form-check form-switch">
      <input data-action="click->filter-tasks#doneUserPartner" class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
      <label class="form-check-label" for="flexSwitchCheckDefault">undone/done</label>
    </div>
  </div>
  <div data-filter-tasks-target="userPartner" class="container pl-2 overflow-fix d-none">
      <% @tasks.where(assigned_to: current_user.household.users.reject { |user| user.id == current_user.id }[0]).and(@tasks.where(done: false)).each do |task| %>
        <%= render "task", task: task %>
      <% end %>
  </div>
  <div data-filter-tasks-target="userPartnerA" class="container pl-2 overflow-fix d-none">
      <% @tasks.where(assigned_to: current_user.household.users.reject { |user| user.id == current_user.id }[0]).and(@tasks.where(done: true)).each do |task| %>
        <%= render "task", task: task %>
      <% end %>
  </div>

   <div class="container d-flex d-none" data-filter-tasks-target="unassignedSwitch">
    <div class="form-check form-switch ">
      <input data-action="click->filter-tasks#doneUnassigned" class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
      <label class="form-check-label" for="flexSwitchCheckDefault">undone/done</label>
    </div>
  </div>
  <div data-filter-tasks-target="unassigned" class="container pl-2 overflow-fix d-none">
    <% @tasks.where(assigned_to: nil).and(@tasks.where(done: false)).each do |task| %>
    <%= render "task", task: task %>
    <% end %>
  </div>
  <div data-filter-tasks-target="unassignedtask" class="container pl-2 overflow-fix d-none">
    <% @tasks.where(assigned_to: nil).and(@tasks.where(done: true)).each do |task| %>
    <%= render "task", task: task %>
    <% end %>
  </div>

</div>

app/views/tasks/new.html.erb
<div class="welcome-message">
  <h1>New Task</h1>
</div>
<div class="container">
  <div class="d-flex justify-content-center">
    <%= link_to "Add from template", templates_path, class: "btn btn-add mt-3" %>
  </div>
  <%= render "form", task: @task %>
  <div style="height: 120px"></div>
</div>

app/views/tasks/score.html.erb
<div class="container task-details-header">
  <h1>Your scores</h1>
</div>


<span class="task-name-card-user1">
  <p><%= current_user.username %> : <%= @user_tasks.pluck(:points).sum %></p>
</span>
<span class="task-name-card-user2">
<p><%= current_user.household.users.reject { |user| user.id == current_user.id }[0].username %> : <%= @partner_tasks.pluck(:points).sum%></p>
</span>
<div class="task-name-card-unassigned">
<p>There are <%=@unassigned_tasks.pluck(:points).sum %> to play for 😎 </p>
<% chart = {
  "You": @user_tasks.pluck(:points).sum,
  "Your partner": @partner_tasks.pluck(:points).sum,
} %>
</div>

<%= pie_chart(chart, colors: ['#9534E0', '#F09206'])%>
<div style="height: 120px"></div>

app/views/tasks/show.html.erb
<div class="container task-details-header">
  <h1>Task details</h1>
</div>

<div class="container">
  <div class= "main-card">
      <%= render "task", task: @task %>

    <div class="task-details">
      <ul>
        <li>Points: <span class="detail"><%=@task.points %></span></li>
        <li>Duration: <span class="detail"><%=@task.duration %></span></li>
        <li>Comments: <span class="detail"><%=@task.comments %></span></li>
        <li>Due date: <span class="detail"><%=@task.due_date %></span></li>
        <li>Contact: <%=@task.contact.nil? ? "" : @task.contact.title %>
        <% if @task.contact.nil? %>
          <ul>
            <li><span class="detail"><i>No contact entered</i></span></li>
          </ul>
        <% else %>
          <ul><span class="detail">
            <li><span class="contact-detail"><i>Name:</i><br> </span><%= @task.contact.nil? ? "" : @task.contact.name  %> </li><br>
            <li><span class="contact-detail"><i>Address:</i><br> </span><%= @task.contact.nil? ? "" : @task.contact.address %></li><br>
            <li><span class="contact-detail"><i>Phone number:</i><br> </span><%= @task.contact.nil? ? "" : @task.contact.phone %></li><br>
          </span>
          </ul>
        <% end %>
        <li>Category: <span class="detail"><%=@task.category.name %></span></li>
        <li>Assigned to: <span class="detail"><%= @task.assigned_to.nil? ? "unassigned" : @task.assigned_to.username %></span></li>
      </ul>
    </div>
  </div>


  <div class="bottom-buttons">
    <div class="bottom-button">
      <%= link_to "Create template", new_task_template_path(@task), class: "btn-flat"%>
      <%= link_to "Duplicate", duplicate_task_path(@task), class: "btn-flat"%>
    </div>
    <div class="bottom-icons">
      <%= link_to task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
      <i class="fa-solid fa-trash"></i>
      <% end %>
      <%= link_to contacts_path do %>
      <i class="fa-regular fa-address-book"></i>
      <% end  %>
      <%= link_to edit_task_path do %>
      <i class="fa-solid fa-pen"></i>
      <% end %>
    </div>

  </div>
  <div style="height: 120px"></div>
</div>