config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "pages#home"
    # root to: "tasks#index"

  get "score", to: "tasks#score", as: :score
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks do
    get :duplicate, on: :member
    resources :templates, only: [:new, :create]
  end
  # Defines the root path route ("/")
  post "tasks/:id/mark_as_done", to: "tasks#mark_as_done", as: :mark_as_done

  resources :templates do
    resources :tasks, only: [:new, :create]
  end
  # root "articles#index"
  resources :contacts
end

# resources :categories, only: [:index, :show] ??
# resources :templates, only: [:index, :show]
# resources :kids, only [:show, :create]
# resources :housholds, only [:index]

app/views/templates/_form.html.erb
<%= simple_form_for @template, :url => {:action => "create"} do |f| %>
  <%= f.input :name %>
  <%= f.input :points %>
  <%# <%= f.input :duration %>
  <%= f.input :type %>
  <%= f.input :comments %>
  <%= f.association :category, collection: Category.all %>
  <div class="d-flex justify-content-center">
    <%= f.button :submit, class: "btn btn-add"%>
  </div>
<% end %>

app/views/templates/_template.html.erb
<div class="template-card">
  <div class="template-infos">
    <% category_hash = {
      "Groceries" => "🥕",
      "Care" => "🐣",
      "Cleaning" => "🧽",
      "Paperwork" => "📄",
      "Planning" => "📅",
      "Maintenance" => "💡"
    } %>
    <p><span><%= category_hash[template.category.name] %>  </span> <%= template.category.name %></p>
    <div class="template-circles">
      <div class="template-points">
        <p><%= template.points %></p>
      </div>
    </div>
  </div>
  <div class="template-name" >
    <h4><%= template.name %></h4>
  </div>
</div>

app/views/templates/edit.html.erb
<div class="welcome-message">
  <h1>Edit template</h1>
</div>
  <div class="main-card">
    <div class="template-name-card justify-content-center">
      <h4><%= @template.name %></h4>
    </div>
<div class= "container overflow-fix">
  <%= simple_form_for @template do |f| %>
    <%= f.input :name %>
    <%= f.input :points %>
    <%# <%= f.input :duration %>
    <%= f.association :category, collection: Category.all %>
      <div class="d-flex justify-content-center">
        <%= f.button :submit, class: "btn btn-add" %>
      </div>
  <% end %>
</div>

app/views/templates/index.html.erb
<div class="container welcome-message">
  <h1>My templates</h1>
</div>

<div class="container pl-2 overflow-fix">
  <div class="search overflow-fix sticky-top mt-3 pt-2">
    <%= form_with url: templates_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "find template"
      %>
      <%= submit_tag "Search", class: "btn btn-flat" %>
    <% end %>
  </div>
  <div>
    <% @templates.each do |template| %>
      <%= link_to template_path(template) do %>
        <%= render "template", template: template %>
      <% end %>
    <% end %>
  </div>
  <div class="text-center">
    <%= link_to "Add new", new_template_path, class: "btn btn-add" %>
  </div>
</div>

app/views/templates/new.html.erb
<div class="welcome-message">
  <h1>New Template</h1>
</div>

<div class="container overflow-fix">
  <%= render "form", template: @template %>
</div>

app/views/templates/show.html.erb
<div class="container template-details-header">
  <h1>Template details</h1>
</div>

<div class="container">
  <div class= "main-card">
    <%= render "template", template: @template %>
    <% category_hash = {
      "Groceries" => "🥕",
      "Care" => "🐣",
      "Cleaning" => "🧽",
      "Paperwork" => "📄",
      "Planning" => "📅",
      "Maintenance" => "💡"
    } %>
    <div class="template-details">
      <ul>
        <li>Points: <span class="template-detail"><%=@template.points %></span></li>
        <li>Duration: <span class="template-detail"><%=@template.duration %></span></li>
        <li>Comments: <span class="template-detail"><%=@template.comments %></span></li>
        <li>Category: <span class="template-detail"><%= category_hash[@template.category.name] %> <%= @template.category.name %></span></li>
      </ul>
    </div>
  </div>
  <div class="bottom-buttons">
    <div class="bottom-button">
      <%= link_to "Create task from template", new_template_task_path(@template), class: "btn btn-add"%>
    </div>
    <div class="bottom-icons">
      <%= link_to template_path(@template), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
      <i class="fa-solid fa-trash"></i>
      <% end %>
      <%= link_to templates_path do %>
      <i class="fa-regular fa-address-book"></i>
      <% end  %>
      <%= link_to edit_template_path do %>
      <i class="fa-solid fa-pen"></i>
      <% end %>
    </div>

  </div>
  <div style="height: 60px"></div>
</div>