config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "pages#home"
    # root to: "tasks#index"

  get "score", to: "tasks#score", as: :score
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks do
    get :duplicate, on: :member
    resources :templates, only: [:new, :create]
  end
  # Defines the root path route ("/")
  post "tasks/:id/mark_as_done", to: "tasks#mark_as_done", as: :mark_as_done

  resources :templates do
    resources :tasks, only: [:new, :create]
  end
  # root "articles#index"
  resources :contacts
end

# resources :categories, only: [:index, :show] ??
# resources :templates, only: [:index, :show]
# resources :kids, only [:show, :create]
# resources :housholds, only [:index]

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom">
  <% if current_user %>
    <% if current_page?(controller:'tasks',action: 'index') %>
      <%= link_to tasks_path, class: "active" do %>
        <i class="fa-solid fa-list-check"></i>
      <% end %>
    <% else %>
      <%= link_to tasks_path do %>
        <i class="fa-solid fa-list-check"></i>
      <% end %>
    <% end  %>

    <%= link_to templates_path do %>
      <i class="fa-regular fa-calendar-plus"></i>
      <%# <i class="fa-solid fa-calendar-days"></i> %>
    <% end  %>

    <% if current_page?(controller:'tasks',action: 'new') %>
      <%= link_to new_task_path, class: "active" do %>
        <i class="fa-solid fa-circle-plus"></i>
      <% end %>
    <% else %>
      <%= link_to new_task_path do %>
        <i class="fa-solid fa-circle-plus"></i>
      <% end %>
    <% end  %>

    <% if current_page?(controller:'contacts',action: 'index') %>
      <%= link_to contacts_path, class: "active" do %>
        <i class="fa-solid fa-address-book"></i>
      <% end  %>
    <% else %>
      <%= link_to contacts_path do %>
        <i class="fa-solid fa-address-book"></i>
      <% end %>
    <% end  %>
    <%= link_to score_path do %>
      <i class="fa-solid fa-chart-column"></i>
    <% end  %>

  <% else %>
    <%# <%= link_to new_user_session_path do %>
      <%# <i class="fa-solid fa-arrow-right-to-bracket"></i> %>
    <%# <% end  %> 
  <% end %>
</div>