config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "pages#home"
    # root to: "tasks#index"

  get "score", to: "tasks#score", as: :score
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks do
    get :duplicate, on: :member
    resources :templates, only: [:new, :create]
  end
  # Defines the root path route ("/")
  post "tasks/:id/mark_as_done", to: "tasks#mark_as_done", as: :mark_as_done

  resources :templates do
    resources :tasks, only: [:new, :create]
  end
  # root "articles#index"
  resources :contacts
end

# resources :categories, only: [:index, :show] ??
# resources :templates, only: [:index, :show]
# resources :kids, only [:show, :create]
# resources :housholds, only [:index]

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :household
  validates :title, presence: true
  validates :name, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = policy_scope(Contact)
    if params[:query].present?
      sql_query = "title ILIKE :query OR name ILIKE :query"
      @contacts = policy_scope(Contact.where(sql_query, query: "%#{params[:query]}%"))
    else
      @contacts = policy_scope(Contact)
    end
  end

  def show
    @contact = Contact.find(params[:id])
    authorize @contact
  end

  def new
    @contact = Contact.new
    @contact.household_id = current_user.household_id
    authorize @contact
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.household_id = current_user.household_id
    authorize @contact
    if @contact.save
      redirect_to contacts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @contact = Contact.find(params[:id])
    authorize @contact
  end

  def update
    @contact = Contact.find(params[:id])
    authorize @contact
    @contact.update(contact_params)
    redirect_to contacts_path
  end

  def destroy
    @contact = Contact.find(params[:id])
    authorize @contact
    @contact.destroy
    redirect_to contacts_path, status: :see_other
  end

  private

  def contact_params
    params.require(:contact).permit(:title, :name, :phone, :address)
  end
end

app/views/contacts/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <%= simple_form_for @contact do |f| %>
        <%= f.input :title, placeholder: "Title", error: "You can't leave it blank"%>
        <%= f.input :name, placeholder: "Name", error: "You can't leave it blank" %>
        <%= f.input :phone, placeholder: "e.g. +49 211 1234567"%>
        <%= f.input :address %>
        <div class="d-flex justify-content-center">
          <%= f.button :submit, class: "btn btn-add" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class="container template-details-header">
  <h1>Edit Contact</h1>
</div>
<div class= "main-card">
    <div class="contact-name-card justify-content-center">
      <h4><%= @contact.name %></h4>
    </div>

<div class="container overflow-fix mt-5">
  <%= render "form", contact: @contact  %>
</div>

app/views/contacts/index.html.erb
<div class="container">
  <div class="search overflow-fix sticky-top sticky-top pt-3 pb-3">
      <%= form_with url: contacts_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "find contact"
        %>
        <%= submit_tag "Search", class: "btn btn-flat" %>
      <% end %>
  </div>
  <div class="container pl-2">
    <div class="list-contacts">
      <% @contacts.each do |contact| %>
        <%= link_to contact_path(contact), class:"contact-item" do %>
            <p><%= contact.title %></p>
        <% end %>
      <% end %>
      <div class="container text-center overflow-fix">
      <%= link_to "Add Contact", new_contact_path, class: "btn btn-add" %>
      </div>
    </div>
    <div style="height: 120px"></div>
  </div>
</div>

app/views/contacts/new.html.erb
<div>
  <div class="welcome-message">
    <h1>New Contact</h1>
  </div>
  <div class="container overflow-fix mt-5">
    <%= render "form", contact: @contact  %>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="container template-details-header">
  <h1>Contact details</h1>
</div>

<div class="container">
  <div class= "main-card">
    <div class="contact-name-card justify-content-center">
      <h4><%= @contact.title %></h4>
    </div>
    <div class="contact-details">
      <%= simple_form_for @contact do |f| %>
        <%= f.input :title %>
        <%= f.input :name %>
        <%= f.input :phone %>
        <%= f.input :address %>
        <div class="d-flex justify-content-center">
        <%= f.button :submit, class: "btn btn-add" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="bottom-buttons">
  <div class="bottom-icons">
    <%= link_to contact_path(@contact), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
    <i class="fa-solid fa-trash"></i>
    <% end %>
    <a class="fa-solid fa-location-dot" href="https://www.google.at/maps/place/<%=@contact.address %>" target="blank"> </a>
    <%= link_to edit_contact_path do %>
    <i class="fa-solid fa-pen"></i>
    <% end %>
  </div>
</div>